### ISSUE TITLE
Why does the bot not work?

### ISSUE THREAD

**Issue by BeckerOFF** [despa1r1337/FSOCIETY-SERVICE-BOT#10]
Why is there an error when starting a request to add a comment? So it’s for joining a group!

**Comment by BeckerOFF** [comment]
Steam profile comments

**Comment by BeckerOFF** [comment]
How to fix it?

**Comment by verdammnis** [comment]
> Why is there an error when starting a request to add a comment? So it’s for joining a group!

apparently your account is limited.

**Comment by BeckerOFF** [comment]
Ok thx
Maybe its true)
