### ISSUE TITLE
[Issue] Reportbot dont work

### ISSUE THREAD

**Issue by JoKerIsCraZy** [despa1r1337/FSOCIETY-SERVICE-BOT#2]
Hey i tested the reporbot on 3 account all got an ingame report and i reportbotted the 12-20 times but they didnt got banned. Did i made something worng?

**Comment by verdammnis** [comment]
> Hey i tested the reporbot on 3 account all got an ingame report and i reportbotted the 12-20 times but they didnt got banned. Did i made something worng?

give me a screenshot  `Target's summary` 3 accounts
