### ISSUE TITLE
Commenting on profiles does not work

### ISSUE THREAD

**Issue by KillSecurite** [despa1r1337/FSOCIETY-SERVICE-BOT#3]
Commenting on profiles does not work https://prnt.sc/r0no0z   steam profile is public

**Comment by verdammnis** [comment]
> Commenting on profiles does not work https://prnt.sc/r0no0z steam profile is public

from the account from which you want to leave a comment-limited ( not spent 5$)

**Comment by KillSecurite** [comment]
interesting because I do it from my main account and nothing happens https://prnt.sc/r0o3l5

**Comment by verdammnis** [comment]
> interesting because I do it from my main account and nothing happens https://prnt.sc/r0o3l5

did you specify the profile ID correctly?

**Comment by KillSecurite** [comment]
yes https://prnt.sc/r0o83g

**Comment by verdammnis** [comment]
> yes https://prnt.sc/r0o83g

I'll be back soon, wait

**Comment by verdammnis** [comment]
@KillSecurite

![image](https://user-images.githubusercontent.com/48297813/74236303-f893a680-4ce1-11ea-9595-c88d347abda6.png)
everything works, make sure that comments are not disabled in your account settings

**Comment by verdammnis** [comment]
if your comments are open, then attach a screenshot of the filled-in window `comment profile` of the program

**Comment by amx22** [comment]
please reportbot program fixed bro not working
