### ISSUE TITLE
Can i contact you somewhere?

### ISSUE THREAD

**Issue by knotti** [despa1r1337/FSOCIETY-SERVICE-BOT#4]
Can i contact you somewhere?
Just wanna asking if you wanna share commendbot fix, if you have it i can offer something back?

**Comment by verdammnis** [comment]
> Can i contact you somewhere?
> Just wanna asking if you wanna share commendbot fix, if you have it i can offer something back?

the program is not mine. and as soon as the developer releases the update, I will immediately upload it here.

**Comment by knotti** [comment]
Okay thanks
