### ISSUE TITLE
 Account and Proxy

### ISSUE THREAD

**Issue by pixelroll** [despa1r1337/FSOCIETY-SERVICE-BOT#5]
Hello,
I wanted to know if it was possible for you to give me the technique to obtain accounts and proxies (for steam) in large quantity and for free?
Thank you

**Comment by verdammnis** [comment]
> Hello,
> I wanted to know if it was possible for you to give me the technique to obtain accounts and proxies (for steam) in large quantity and for free?
> Thank you

accounts - https://accgen.cathook.club/

proxies-  addon.to or https://top-proxies.ru/

**Comment by pixelroll** [comment]
addon.to need invite code

**Comment by pixelroll** [comment]
and it's not free

**Comment by verdammnis** [comment]
> and it's not free

did you want to find for free? ; /

**Comment by verdammnis** [comment]
for what purposes will you use the program?

**Comment by verdammnis** [comment]
I am kind today so I can give an invite to addon . write, where can I contact you?

**Comment by pixelroll** [comment]
You are a good person, thank you. You can contact me on discord (Pixelroll # 4299).

**Comment by verdammnis** [comment]
> You are a good person, thank you. You can contact me on discord (Pixelroll # 4299).

Add me
