### ISSUE TITLE
please update 

### ISSUE THREAD

**Issue by ilovegame1985** [despa1r1337/FSOCIETY-SERVICE-BOT#7]
I love this program 
please update

**Comment by verdammnis** [comment]
> I love this program
> please update

If the developer releases an update, I will immediately post it here.

Use this - https://github.com/BeepIsla/csgo-commend-bot. 
Same thing, only without metro

**Comment by ilovegame1985** [comment]
ok sir

**Comment by ilovegame1985** [comment]
thank you!
