### ISSUE TITLE
[Issue] Problem with REPORT BOT and COMMEND BOT

### ISSUE THREAD

**Issue by HITMANek210** [despa1r1337/FSOCIETY-SERVICE-BOT#8]
Failed to send commend (game coordinator response timeout)
Failed to send report (game coordinator response timeout)

**Comment by verdammnis** [comment]
> Failed to send commend (game coordinator response timeout)
> Failed to send report (game coordinator response timeout)

! Fsbot patched ! 
https://github.com/despa1r1337/FSOCIETY-SERVICE-BOT/blob/master/CHANGELOG.md

Use: 

ReportBot (14.03.2020) - https://github.com/despa1r1337/ReportBot-v2

CommendBot - https://github.com/BeepIsla/csgo-commend-bot
