### ISSUE TITLE
accounts does not work

### ISSUE THREAD

**Issue by omidonrails** [despa1r1337/FSOCIETY-SERVICE-BOT#9]
all my accounts it's active and steam gaurd disabled but i get this error :
Failed to send commend (game coordinator response timeout)
what's the problem ? how can solve ?

**Comment by verdammnis** [comment]
> all my accounts it's active and steam gaurd disabled but i get this error :
> Failed to send commend (game coordinator response timeout)
> what's the problem ? how can solve ?

! Fsbot `reportbot` and `commendbot` patched !
https://github.com/despa1r1337/FSOCIETY-SERVICE-BOT/blob/master/CHANGELOG.md

Use:

ReportBot (14.03.2020) - https://github.com/despa1r1337/ReportBot-v2

CommendBot - https://github.com/BeepIsla/csgo-commend-bot
